BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ListeningFilm] ADD [strUrl] NVARCHAR(1000);

-- AddForeignKey
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_defaultLanguageId_fkey] FOREIGN KEY ([defaultLanguageId]) REFERENCES [dbo].[Language]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
