// TYPES
import { JwtPayload, UserSession } from "@/src/infrastructure/auth/authTypes"


// DECODES JWT PAYLOAD WITHOUT VERIFYING SIGNATURE
export function decodeJwtPayload(token: string): JwtPayload | null {

    try {

        const parts = token.split(".")
        if (parts.length !== 3) return null

        const payload = parts[1]
        const decoded = Buffer.from(payload, "base64url").toString("utf-8")

        return JSON.parse(decoded)
        
    } catch {

        return null
    }
}


// IT RETRIEVES USER INFO FROM A JWT GENERATED BY ASP.NET CORE AND CREATES USER SESSION OBJECT
export function extractUserSession(payload: JwtPayload): UserSession | null {

    const userId = payload["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"] as string
    const userName = payload["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"] as string
    const email = payload["email"] as string

    if (!userId) return null

    return { userId, userName: userName ?? "", email: email ?? "" }
}


// CHECKS WHETHER A JWT TOKEN HAS EXPIRED BASED ON ITS 'exp' CLAIM
export function isTokenExpired(token: string): boolean {

    const payload = decodeJwtPayload(token)
    if (!payload || !payload.exp) return true

    const expiration = (payload.exp as number) * 1000
    return Date.now() >= expiration
}
